FROM public.ecr.aws/lambda/nodejs:20

WORKDIR ${LAMBDA_TASK_ROOT}

COPY package*.json ./
RUN npm ci --only=production

COPY src/backend ./src/backend
RUN npx prisma generate

CMD ["src/backend/lambda/handler.handler"]
