// db/cityLandmarks.js — reference: the signature landmarks / places of interest for each Explore city, keyed
// by the city's primary IATA (ExploreCity.iataCode). Used to fetch a slideshow of recognisable places (one
// photo per landmark) rather than generic "city" photos. landmarksFor() returns [] for an unknown code so the
// caller can fall back to a generic query.
const CITY_LANDMARKS = {
  EZE: ["Obelisco", "Casa Rosada", "Teatro Colon", "Caminito La Boca"],
  MEL: ["Flinders Street Station", "Federation Square", "Royal Botanic Gardens", "Brighton Bathing Boxes"],
  SYD: ["Sydney Opera House", "Sydney Harbour Bridge", "Bondi Beach", "Darling Harbour"],
  VIE: ["Schonbrunn Palace", "St Stephens Cathedral", "Belvedere Palace", "Hofburg"],
  BGI: ["Carlisle Bay Barbados", "Garrison Savannah", "St Nicholas Abbey Barbados", "Bathsheba Beach"],
  BRU: ["Grand Place Brussels", "Atomium", "Manneken Pis", "Royal Palace of Brussels"],
  GIG: ["Christ the Redeemer", "Sugarloaf Mountain", "Copacabana Beach", "Selaron Steps"],
  GRU: ["Paulista Avenue", "Ibirapuera Park", "Sao Paulo Cathedral", "Municipal Theatre Sao Paulo"],
  YYZ: ["CN Tower", "Royal Ontario Museum", "Casa Loma", "Toronto City Hall"],
  YVR: ["Stanley Park Vancouver", "Capilano Suspension Bridge", "Granville Island", "Canada Place"],
  SCL: ["Cerro San Cristobal", "Plaza de Armas Santiago", "La Moneda Palace", "Sky Costanera"],
  PEK: ["Forbidden City", "Great Wall of China", "Temple of Heaven", "Tiananmen Square"],
  PVG: ["The Bund Shanghai", "Oriental Pearl Tower", "Yu Garden", "Shanghai Tower"],
  BOG: ["Monserrate", "Plaza Bolivar Bogota", "Gold Museum Bogota", "La Candelaria Bogota"],
  SJO: ["Teatro Nacional Costa Rica", "National Museum Costa Rica", "Metropolitan Cathedral San Jose", "La Sabana Park"],
  DBV: ["Dubrovnik Old Town Walls", "Stradun", "Fort Lovrijenac", "Lokrum Island"],
  SPU: ["Diocletians Palace", "Split Riva Promenade", "Marjan Hill", "Cathedral of St Domnius"],
  HAV: ["Malecon Havana", "El Capitolio Havana", "Plaza Vieja Havana", "Morro Castle Havana"],
  PRG: ["Charles Bridge", "Prague Castle", "Old Town Square Prague", "Prague Astronomical Clock"],
  CPH: ["Nyhavn", "Little Mermaid Copenhagen", "Tivoli Gardens", "Amalienborg"],
  CAI: ["Pyramids of Giza", "Great Sphinx", "Egyptian Museum", "Khan el-Khalili"],
  HRG: ["Giftun Island", "Hurghada Marina", "Red Sea coral reef", "El Mina Mosque Hurghada"],
  NAN: ["Garden of the Sleeping Giant", "Sri Siva Subramaniya Temple", "Denarau Island", "Mamanuca Islands"],
  LYS: ["Basilica of Notre-Dame de Fourviere", "Vieux Lyon", "Place Bellecour", "Parc de la Tete d'Or"],
  NCE: ["Promenade des Anglais", "Vieux Nice", "Castle Hill Nice", "Place Massena"],
  CDG: ["Eiffel Tower", "Louvre Museum", "Notre-Dame de Paris", "Arc de Triomphe"],
  BER: ["Brandenburg Gate", "Reichstag Building", "East Side Gallery", "Museum Island Berlin"],
  FRA: ["Romerberg Frankfurt", "Main Tower Frankfurt", "Frankfurt Cathedral", "Eiserner Steg"],
  MUC: ["Marienplatz", "Neuschwanstein Castle", "English Garden Munich", "Frauenkirche Munich"],
  ATH: ["Acropolis of Athens", "Parthenon", "Plaka Athens", "Temple of Olympian Zeus"],
  HER: ["Knossos Palace", "Koules Fortress", "Heraklion Archaeological Museum", "Lion Square Heraklion"],
  JTR: ["Oia Santorini", "Fira Santorini", "Santorini blue domes", "Santorini caldera"],
  HKG: ["Victoria Peak", "Victoria Harbour", "Tian Tan Buddha", "Temple Street Hong Kong"],
  KEF: ["Hallgrimskirkja", "Sun Voyager Reykjavik", "Harpa Concert Hall", "Blue Lagoon Iceland"],
  DEL: ["India Gate", "Red Fort", "Qutub Minar", "Lotus Temple"],
  GOI: ["Basilica of Bom Jesus", "Fort Aguada", "Palolem Beach", "Dudhsagar Falls"],
  BOM: ["Gateway of India", "Marine Drive Mumbai", "Chhatrapati Shivaji Terminus", "Taj Mahal Palace Hotel"],
  DPS: ["Tanah Lot", "Uluwatu Temple", "Tegallalang Rice Terraces", "Ubud Monkey Forest"],
  CGK: ["National Monument Monas", "Istiqlal Mosque Jakarta", "Kota Tua Jakarta", "Grand Indonesia"],
  DUB: ["Trinity College Dublin", "Temple Bar Dublin", "Guinness Storehouse", "Ha'penny Bridge"],
  TLV: ["Old Jaffa", "Tel Aviv Promenade", "Rothschild Boulevard", "Carmel Market Tel Aviv"],
  MXP: ["Duomo di Milano", "Galleria Vittorio Emanuele II", "Sforza Castle", "La Scala Milan"],
  FCO: ["Colosseum", "Trevi Fountain", "St Peters Basilica", "Pantheon Rome"],
  VCE: ["St Marks Square Venice", "Rialto Bridge", "Grand Canal Venice", "Doge's Palace"],
  MBJ: ["Doctor's Cave Beach", "Rose Hall Great House", "Montego Bay Hip Strip", "Dunn's River Falls"],
  KIX: ["Fushimi Inari Shrine", "Kinkaku-ji", "Arashiyama Bamboo Grove", "Kiyomizu-dera"],
  HND: ["Senso-ji", "Tokyo Tower", "Shibuya Crossing", "Meiji Shrine"],
  AMM: ["Amman Citadel", "Roman Theatre Amman", "Rainbow Street Amman", "King Abdullah I Mosque"],
  NBO: ["Nairobi National Park", "Giraffe Centre Nairobi", "David Sheldrick Wildlife Trust", "Karen Blixen Museum"],
  KUL: ["Petronas Towers", "Batu Caves", "KL Tower", "Merdeka Square Kuala Lumpur"],
  MLE: ["Male Friday Mosque", "Sultan Park Male", "Rasfannu Beach", "Male waterfront"],
  MRU: ["Caudan Waterfront", "Aapravasi Ghat", "Port Louis Central Market", "Fort Adelaide Mauritius"],
  CUN: ["Chichen Itza", "Playa Delfines Cancun", "El Rey Ruins", "Isla Mujeres"],
  MEX: ["Zocalo Mexico City", "Palacio de Bellas Artes", "Teotihuacan", "Chapultepec Castle"],
  CMN: ["Hassan II Mosque", "Casablanca Corniche", "Old Medina Casablanca", "Mohammed V Square"],
  RAK: ["Jemaa el-Fnaa", "Koutoubia Mosque", "Bahia Palace", "Majorelle Garden"],
  AMS: ["Amsterdam canals", "Rijksmuseum", "Anne Frank House", "Van Gogh Museum"],
  AKL: ["Sky Tower Auckland", "Auckland Harbour Bridge", "Mount Eden", "Waiheke Island"],
  LOS: ["Lekki Conservation Centre", "Nike Art Gallery Lagos", "Tarkwa Bay", "National Theatre Lagos"],
  OSL: ["Oslo Opera House", "Vigeland Park", "Akershus Fortress", "Holmenkollen"],
  MCT: ["Sultan Qaboos Grand Mosque", "Mutrah Souq", "Royal Opera House Muscat", "Al Jalali Fort"],
  LIM: ["Plaza Mayor Lima", "Miraflores Lima", "Huaca Pucllana", "Magic Water Circuit Lima"],
  CEB: ["Magellan's Cross", "Basilica del Santo Nino", "Temple of Leah", "Kawasan Falls"],
  MNL: ["Intramuros", "Rizal Park", "San Agustin Church Manila", "Manila Bay"],
  FAO: ["Faro Old Town", "Ria Formosa", "Faro Cathedral", "Faro Marina"],
  LIS: ["Belem Tower", "Jeronimos Monastery", "Tram 28 Lisbon", "Alfama Lisbon"],
  OPO: ["Dom Luis I Bridge", "Ribeira Porto", "Livraria Lello", "Clerigos Tower"],
  DOH: ["Museum of Islamic Art Doha", "Souq Waqif", "The Pearl Qatar", "Katara Cultural Village"],
  SEZ: ["Anse Source d'Argent", "Victoria Market Seychelles", "Morne Seychellois", "Beau Vallon"],
  SIN: ["Marina Bay Sands", "Gardens by the Bay", "Merlion", "Sentosa"],
  CPT: ["Table Mountain", "V&A Waterfront", "Cape of Good Hope", "Boulders Beach"],
  JNB: ["Apartheid Museum", "Constitution Hill Johannesburg", "Gold Reef City", "Nelson Mandela Bridge"],
  ICN: ["Gyeongbokgung Palace", "N Seoul Tower", "Bukchon Hanok Village", "Myeongdong"],
  BCN: ["Sagrada Familia", "Park Guell", "La Rambla Barcelona", "Casa Batllo"],
  MAD: ["Royal Palace of Madrid", "Plaza Mayor Madrid", "Retiro Park", "Prado Museum"],
  AGP: ["Alcazaba Malaga", "Malaga Cathedral", "Gibralfaro Castle", "Picasso Museum Malaga"],
  CMB: ["Gangaramaya Temple", "Galle Face Green", "Lotus Tower Colombo", "Independence Square Colombo"],
  ARN: ["Gamla Stan", "Vasa Museum", "Royal Palace Stockholm", "Stockholm City Hall"],
  GVA: ["Jet d'Eau", "Lake Geneva", "St Pierre Cathedral Geneva", "Flower Clock Geneva"],
  ZRH: ["Grossmunster", "Lake Zurich", "Bahnhofstrasse", "Niederdorf Zurich"],
  JRO: ["Mount Kilimanjaro", "Moshi Tanzania", "Materuni Waterfall", "Chagga village"],
  ZNZ: ["Stone Town Zanzibar", "Nungwi Beach", "Prison Island Zanzibar", "Jozani Forest"],
  BKK: ["Grand Palace Bangkok", "Wat Arun", "Wat Pho", "Chatuchak Market"],
  CNX: ["Wat Phra That Doi Suthep", "Chiang Mai Old City", "Chiang Mai Sunday Walking Street", "Elephant Nature Park"],
  HKT: ["Big Buddha Phuket", "Patong Beach", "Phi Phi Islands", "Phuket Old Town"],
  AYT: ["Hadrian's Gate Antalya", "Kaleici Antalya", "Duden Waterfalls", "Konyaalti Beach"],
  IST: ["Hagia Sophia", "Blue Mosque", "Grand Bazaar Istanbul", "Bosphorus"],
  AUH: ["Sheikh Zayed Grand Mosque", "Louvre Abu Dhabi", "Emirates Palace", "Abu Dhabi Corniche"],
  DXB: ["Burj Khalifa", "Burj Al Arab", "Palm Jumeirah", "Dubai Marina"],
  EDI: ["Edinburgh Castle", "Royal Mile", "Arthur's Seat", "Calton Hill"],
  LHR: ["Big Ben", "Tower Bridge", "Buckingham Palace", "London Eye"],
  MAN: ["Old Trafford", "Manchester Town Hall", "Northern Quarter Manchester", "John Rylands Library"],
  LAX: ["Hollywood Sign", "Griffith Observatory", "Santa Monica Pier", "Venice Beach California"],
  MIA: ["South Beach Miami", "Ocean Drive Miami", "Wynwood Walls", "Little Havana"],
  JFK: ["Statue of Liberty", "Times Square", "Central Park", "Brooklyn Bridge"],
  SFO: ["Golden Gate Bridge", "Alcatraz", "Lombard Street", "Fisherman's Wharf"],
  HAN: ["Hoan Kiem Lake", "Hanoi Old Quarter", "Temple of Literature", "Ho Chi Minh Mausoleum"],
  SGN: ["Saigon Notre-Dame Cathedral", "Ben Thanh Market", "War Remnants Museum", "Bitexco Financial Tower"],
};

function landmarksFor(iataCode) {
  return CITY_LANDMARKS[iataCode] || [];
}

module.exports = { CITY_LANDMARKS, landmarksFor };
